language: java
jdk:
- openjdk8
dist: bionic
before_install:
- pyenv global 3.6
- pip install -U --user pip six numpy wheel mock grpcio grpcio-tools
script:
- cd deep-learning-on-flink && mvn -DskipITs=true clean package
branches:
  except:
  - appveyor